version: '3.3'
services:
  api:
    container_name: 'api'
    build: .
    ports:
      - '8089:8089'
    volumes:
      - './api:/go/src/app'
    depends_on:
      - 'mongodb'
    environment:
      - "API_URL:/api/v1/products"
      - "MONGO_URI:mongodb://db:27017"
      - "MONGO_DATABASE:db"
      - "MONGO_PRODUCTS_COLLECTION:products"
      - "HOST:localhost"
      - "PORT:8989"  
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - '27100:27017'